name: 'Terraform'

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: self-hosted
    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      env:
        TF_VAR_name: ngalipot2
      run: terraform plan -input=false -out plan.out

    - name: Display plan
      run: terraform show -no-color plan.out >> $GITHUB_STEP_SUMMARY

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v4
      with:
        name: my-plan
        path: plan.out
        retention-days: 5

  terraform-apply:
    name: 'Terraform Apply'
    runs-on: self-hosted
    needs: terraform-plan
    environment: production
    defaults:
      run:
        shell: bash

    steps:

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Echo name
      run: echo ${{ vars.TF_VAR_NAME }}

    - name: Download Terraform Plan
      uses: actions/download-artifact@v4
      with:
        name: my-plan
    
    - name: Terraform Apply
      run: terraform apply -input=false plan.out
